language: ruby
rvm:
  - '1.9.3'
  - '2.0.0-p648'
  - '2.1.7'
  - '2.2.5'
  - '2.3.1'
script:
  - "ruby -r cgi index.cgi 'title_line=true&target=1+2+3'"
  - "ruby -r cgi index.cgi 'title_line=false&target=1+2'"
  - "ruby -r cgi index.cgi target=1+2"
  - "ruby -r cgi index.cgi 'title_line=true&target=1+2&type=text'"
notifications:
  irc:
    use_notice: true
    channels: 
      - 'irc.trpg.net#koi-chan'
    on_success: always
    on_failure: always
    template:
      - '%{repository_slug} #%{build_number} %{branch} - %{commit} -> %{result}'
      - '変更履歴: %{compare_url}'
      - 'ステータス: %{build_url}'
  email: false
