language: ruby
rvm:
  - '1.8'
  - '1.9.3'
  - '2.0.0'
  - '2.1.0'
  - '2.2.3'
script:
  - 'ruby shell.rb 1 2 3'
  - "ruby -r cgi detatoko_1line_charasheet.cgi 'title_line=true&target=1+2+3'"
  - "ruby -r cgi detatoko_1line_charasheet.cgi 'title_line=false&target=1+2'"
  - "ruby -r cgi detatoko_1line_charasheet.cgi target=1+2"
notifications:
  irc:
    channels: 
      - 'irc.cre.jp#koi-chan'
    on_success: change
    on_failure: always
